name: Unit Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - magento2

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go test